name: Builtin Test

on:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:


jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
            submodules: 'true'

      - name: Test
        env: 
            TERM: xterm-256color
        id: test
        run: |
            ./builtin_unit_tester.sh > output.txt

      - name: Check test status
        run: |
          if grep -q "KO" output.txt; then
            exit 1
          fi
