name: Build

on:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
            submodules: 'true'
      - name: Install Dependencies
        run: |
          set -x
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
          brew update
          brew install readline
  
      - name: Norminette
        run: norminette minishell

      - name: Build
        run: make -C ${{github.workspace}}
